### ISSUE TITLE
Bot and some questions

### ISSUE THREAD

**Issue by GreYzZ** [mvegter/CSGO-Coinflip#1]
Hello,
will you also release the Bot for deposit and withdraw?
And will you go on working on the script like do some addition and some stuff?

**Comment by mvegter** [comment]
No and no. You can buy the corresponding bot and I won't be adding additional features for free.

**Comment by GreYzZ** [comment]
@mvegter, okay what does the Bot cost? And is it a NodeJS Bot?

**Comment by mvegter** [comment]
@GreYzZ It is a NodeJS Bot, for pricing and other details will be discussed in a private chat.

**Comment by GreYzZ** [comment]
@mvegter, okay you can add me on steam 
http://steamcommunity.com/id/GreYzZ_DE/
